project:
  type: book
  output-dir: docs
  resources:
    - CNAME

book:
  title: "NLP: From Simple to Spectacular"
  author: "Spencer Mitchell"
  chapters:
    - index.qmd
    - intro.qmd
    - 01_data/data.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-line-numbers: true

email-obfuscation: javascript

execute:
  freeze: auto
