project:
  type: book
  output-dir: docs
  resources:
    - CNAME

book:
  title: "NLP: From Simple to Spectacular"
  author: "Spencer Mitchell"
  chapters:
    - index.qmd
    - chapter/01_data/data.ipynb
    - chapter/02_baseline/baseline_classifier.ipynb
    - chapter/03_oner/oner.ipynb
    - chapter/04_boc/boc.ipynb
    - chapter/05_decision_tree/decision_tree.ipynb
    - chapter/bonus/cleaning_data/cleaning_data.ipynb
    - chapter/bonus/quality_vs_quantity/quality_vs_quantity.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-line-numbers: true

email-obfuscation: javascript

execute:
  freeze: auto
