project:
  type: book
  output-dir: docs
  resources:
    - CNAME

book:
  title: "NLP: From Simple to Spectacular"
  author: "Spencer Mitchell"
  chapters:
    - index.qmd
    - chapter/01_data/data.ipynb
    - part: "Classification"
      chapters:
      - chapter/02_baseline/baseline_classifier.ipynb
      - chapter/03_oner/oner.ipynb
    - part: "Representation learning"
      chapters:
      - chapter/04_boc/boc.ipynb
    - part: "Classification"
      chapters:
      - chapter/05_decision_tree/decision_tree.ipynb
      - chapter/06_loss/loss.ipynb
    - part: "Representation learning"
      chapters:
      - chapter/07_bow/bow.ipynb
      - chapter/08_tokens/tokens.ipynb
    - part: "Generative AI"
      chapters:
      - chapter/09_unigram/unigram.ipynb
    - part: "Bonus chapters"
      chapters:
      - chapter/bonus/cleaning_data/cleaning_data.ipynb
      - chapter/bonus/quality_vs_quantity/quality_vs_quantity.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-line-numbers: true

email-obfuscation: javascript

execute:
  freeze: auto
