channels:
- conda-forge
- defaults
dependencies:
- ipython=8.26.0
- jupyter=1.0.0
- pip=24.3.1
- python=3.12.4
- scikit-learn=1.6.0
- seaborn=0.13.2
- tqdm=4.66.5
- pip:
  - git+https://github.com/spenceforce/NLP-Simple-to-Spectacular
name: nlp_simple_to_spectacular
